
# reddit/__init__.py

# --- Resources from 'reddit' ---
from . import Account
from . import Announcements
from . import Captcha
from . import Collections
from . import Emoji
from . import Flair
from . import LinksAndComments
from . import Listings
from . import Live
from . import Messages
from . import Misc
from . import Moderation
from . import Modmail
from . import Modnote
from . import Multis
from . import Search
from . import Subreddits
from . import Users
from . import Widgets
from . import Wiki

import importlib
import os
import json
import tempfile
from common_utils.error_handling import get_package_error_mode
from .SimulationEngine.db import DB, load_state, save_state
from common_utils.init_utils import create_error_simulator, resolve_function_import
from reddit.SimulationEngine import utils
from reddit import SimulationEngine

# Get the directory of the current file
_INIT_PY_DIR = os.path.dirname(__file__)

# Create error simulator using the utility function
error_simulator = create_error_simulator(_INIT_PY_DIR)

# Get the error mode for the package
ERROR_MODE = get_package_error_mode()

# Function map
_function_map = {
  "create_or_update_subreddit_widget": "reddit.Widgets.post_api_widget",
  "delete_subreddit_widget": "reddit.Widgets.delete_api_widget_widget_id",
  "get_widget_image_s3_upload_lease": "reddit.Widgets.post_api_widget_image_upload_s3",
  "reorder_subreddit_widgets": "reddit.Widgets.patch_api_widget_order_section",
  "get_all_subreddit_widgets": "reddit.Widgets.get_api_widgets",
  "get_oauth_scopes": "reddit.Misc.get_api_v1_scopes",
  "delete_moderator_note": "reddit.Modnote.delete_api_mod_notes",
  "get_recent_moderator_notes_for_user": "reddit.Modnote.get_api_mod_notes_recent",
  "get_search": "reddit.Search.get_search",
  "get_best_posts": "reddit.Listings.get_best",
  "get_posts_by_id": "reddit.Listings.get_by_id_names",
  "get_post_comments": "reddit.Listings.get_comments_article",
  "get_controversial_posts": "reddit.Listings.get_controversial",
  "find_duplicate_posts": "reddit.Listings.get_duplicates_article",
  "get_hot_posts": "reddit.Listings.get_hot",
  "get_new_posts": "reddit.Listings.get_new",
  "get_rising_posts": "reddit.Listings.get_rising",
  "get_top_posts": "reddit.Listings.get_top",
  "get_sorted_posts": "reddit.Listings.get_sort",
  "bulk_mark_modmail_as_read": "reddit.Modmail.post_api_mod_bulk_read",
  "get_modmail_conversations": "reddit.Modmail.get_api_mod_conversations",
  "get_modmail_conversation_details": "reddit.Modmail.get_api_mod_conversations_conversation_id",
  "approve_modmail_conversation": "reddit.Modmail.post_api_mod_conversations_conversation_id_approve",
  "archive_modmail_conversation": "reddit.Modmail.post_api_mod_conversations_conversation_id_archive",
  "disapprove_modmail_conversation": "reddit.Modmail.post_api_mod_conversations_conversation_id_disapprove",
  "remove_modmail_conversation_highlight": "reddit.Modmail.delete_api_mod_conversations_conversation_id_highlight",
  "mute_user_in_modmail_conversation": "reddit.Modmail.post_api_mod_conversations_conversation_id_mute",
  "temp_ban_user_via_modmail": "reddit.Modmail.post_api_mod_conversations_conversation_id_temp_ban",
  "unarchive_modmail_conversation": "reddit.Modmail.post_api_mod_conversations_conversation_id_unarchive",
  "unban_user_via_modmail": "reddit.Modmail.post_api_mod_conversations_conversation_id_unban",
  "unmute_user_in_modmail_conversation": "reddit.Modmail.post_api_mod_conversations_conversation_id_unmute",
  "mark_modmail_conversations_as_read": "reddit.Modmail.post_api_mod_conversations_read",
  "list_modmail_accessible_subreddits": "reddit.Modmail.get_api_mod_conversations_subreddits",
  "mark_modmail_conversations_as_unread": "reddit.Modmail.post_api_mod_conversations_unread",
  "get_unread_modmail_conversation_count": "reddit.Modmail.get_api_mod_conversations_unread_count",
  "clear_flair_templates": "reddit.Flair.post_api_clearflairtemplates",
  "delete_user_flair": "reddit.Flair.post_api_deleteflair",
  "delete_flair_template": "reddit.Flair.post_api_deleteflairtemplate",
  "set_user_flair": "reddit.Flair.post_api_flair",
  "reorder_flair_templates": "reddit.Flair.patch_api_flair_template_order",
  "configure_flair_settings": "reddit.Flair.post_api_flairconfig",
  "set_user_flairs_via_csv": "reddit.Flair.post_api_flaircsv",
  "get_flair_list": "reddit.Flair.get_api_flairlist",
  "get_flair_options": "reddit.Flair.post_api_flairselector",
  "create_or_update_flair_template": "reddit.Flair.post_api_flairtemplate",
  "create_or_update_flair_template_v2": "reddit.Flair.post_api_flairtemplate_v2",
  "get_link_flair_templates_legacy": "reddit.Flair.get_api_link_flair",
  "get_link_flair_templates": "reddit.Flair.get_api_link_flair_v2",
  "select_link_flair": "reddit.Flair.post_api_selectflair",
  "set_flair_enabled_status": "reddit.Flair.post_api_setflairenabled",
  "get_user_flair_templates_legacy": "reddit.Flair.get_api_user_flair",
  "get_user_flair_templates": "reddit.Flair.get_api_user_flair_v2",
  "get_global_announcements": "reddit.Announcements.get_api_announcements_v1",
  "hide_announcements": "reddit.Announcements.post_api_announcements_v1_hide",
  "mark_announcements_as_read": "reddit.Announcements.post_api_announcements_v1_read",
  "mark_all_announcements_as_read": "reddit.Announcements.post_api_announcements_v1_read_all",
  "get_unread_announcements": "reddit.Announcements.get_api_announcements_v1_unread",
  "delete_saved_filter_path": "reddit.Multis.delete_api_filter_filterpath",
  "remove_subreddit_from_filter_path": "reddit.Multis.delete_api_filter_filterpath_r_srname",
  "copy_multireddit": "reddit.Multis.post_api_multi_copy",
  "get_my_multireddits": "reddit.Multis.get_api_multi_mine",
  "get_user_public_multireddits": "reddit.Multis.get_api_multi_user_username",
  "delete_multireddit": "reddit.Multis.delete_api_multi_multipath",
  "get_multireddit_description": "reddit.Multis.get_api_multi_multipath_description",
  "remove_subreddit_from_multireddit": "reddit.Multis.delete_api_multi_multipath_r_srname",
  "get_my_identity": "reddit.Account.get_api_v1_me",
  "get_my_blocked_users": "reddit.Account.get_api_v1_me_blocked",
  "get_my_friends": "reddit.Account.get_api_v1_me_friends",
  "get_my_karma_breakdown": "reddit.Account.get_api_v1_me_karma",
  "get_my_preferences": "reddit.Account.get_api_v1_me_prefs",
  "update_my_preferences": "reddit.Account.patch_api_v1_me_prefs",
  "get_my_trophies": "reddit.Account.get_api_v1_me_trophies",
  "get_detailed_blocked_users": "reddit.Account.get_prefs_blocked",
  "get_detailed_friends_info": "reddit.Account.get_prefs_friends",
  "get_my_messaging_preferences": "reddit.Account.get_prefs_messaging",
  "get_my_trusted_users": "reddit.Account.get_prefs_trusted",
  "get_preferences_by_category": "reddit.Account.get_prefs_where",
  "get_live_threads_by_id": "reddit.Live.get_api_live_by_id_names",
  "create_live_thread": "reddit.Live.post_api_live_create",
  "get_featured_live_thread": "reddit.Live.get_api_live_happening_now",
  "accept_live_thread_contributor_invite": "reddit.Live.post_api_live_thread_accept_contributor_invite",
  "close_live_thread": "reddit.Live.post_api_live_thread_close_thread",
  "delete_live_thread_update": "reddit.Live.post_api_live_thread_delete_update",
  "edit_live_thread_settings": "reddit.Live.post_api_live_thread_edit",
  "hide_live_thread_discussion": "reddit.Live.post_api_live_thread_hide_discussion",
  "invite_live_thread_contributor": "reddit.Live.post_api_live_thread_invite_contributor",
  "leave_live_thread_contributor_role": "reddit.Live.post_api_live_thread_leave_contributor",
  "report_live_thread": "reddit.Live.post_api_live_thread_report",
  "remove_live_thread_contributor": "reddit.Live.post_api_live_thread_rm_contributor",
  "revoke_live_thread_contributor_invite": "reddit.Live.post_api_live_thread_rm_contributor_invite",
  "set_live_thread_contributor_permissions": "reddit.Live.post_api_live_thread_set_contributor_permissions",
  "strike_live_thread_update": "reddit.Live.post_api_live_thread_strike_update",
  "unhide_live_thread_discussion": "reddit.Live.post_api_live_thread_unhide_discussion",
  "add_live_thread_update": "reddit.Live.post_api_live_thread_update",
  "get_live_thread_details": "reddit.Live.get_live_thread",
  "get_live_thread_metadata": "reddit.Live.get_live_thread_about",
  "get_live_thread_contributors": "reddit.Live.get_live_thread_contributors",
  "get_live_thread_discussions": "reddit.Live.get_live_thread_discussions",
  "get_live_thread_update_details": "reddit.Live.get_live_thread_updates_update_id",
  "get_edited_items": "reddit.Moderation.get_about_edited",
  "get_moderation_log": "reddit.Moderation.get_about_log",
  "get_modqueue_items": "reddit.Moderation.get_about_modqueue",
  "get_reported_items": "reddit.Moderation.get_about_reports",
  "get_spam_items": "reddit.Moderation.get_about_spam",
  "get_unmoderated_items": "reddit.Moderation.get_about_unmoderated",
  "get_moderated_items_by_category": "reddit.Moderation.get_about_location",
  "accept_moderator_invite": "reddit.Moderation.post_api_accept_moderator_invite",
  "approve_item": "reddit.Moderation.post_api_approve",
  "distinguish_item": "reddit.Moderation.post_api_distinguish",
  "ignore_item_reports": "reddit.Moderation.post_api_ignore_reports",
  "leave_contributor_status": "reddit.Moderation.post_api_leavecontributor",
  "leave_moderator_status": "reddit.Moderation.post_api_leavemoderator",
  "remove_item": "reddit.Moderation.post_api_remove",
  "show_removed_comment": "reddit.Moderation.post_api_show_comment",
  "snooze_item_reports": "reddit.Moderation.post_api_snooze_reports",
  "unignore_item_reports": "reddit.Moderation.post_api_unignore_reports",
  "unsnooze_item_reports": "reddit.Moderation.post_api_unsnooze_reports",
  "update_post_crowd_control_level": "reddit.Moderation.post_api_update_crowd_control_level",
  "get_subreddit_stylesheet": "reddit.Moderation.get_stylesheet",
  "block_user": "reddit.Users.post_api_block_user",
  "add_friend": "reddit.Users.post_api_friend",
  "report_user": "reddit.Users.post_api_report_user",
  "set_user_permissions": "reddit.Users.post_api_setpermissions",
  "remove_friend": "reddit.Users.post_api_unfriend",
  "get_user_data_by_account_ids": "reddit.Users.get_api_user_data_by_account_ids",
  "check_username_availability": "reddit.Users.get_api_username_available",
  "remove_friend_by_username": "reddit.Users.delete_api_v1_me_friends_username",
  "get_user_trophies": "reddit.Users.get_api_v1_user_username_trophies",
  "get_user_profile_info": "reddit.Users.get_user_username_about",
  "get_user_comments": "reddit.Users.get_user_username_comments",
  "get_user_downvoted_posts": "reddit.Users.get_user_username_downvoted",
  "get_user_gilded_posts": "reddit.Users.get_user_username_gilded",
  "get_user_hidden_posts": "reddit.Users.get_user_username_hidden",
  "get_user_overview": "reddit.Users.get_user_username_overview",
  "get_user_saved_posts": "reddit.Users.get_user_username_saved",
  "get_user_submitted_posts": "reddit.Users.get_user_username_submitted",
  "get_user_upvoted_posts": "reddit.Users.get_user_username_upvoted",
  "get_user_content_by_category": "reddit.Users.get_user_username_where",
  "add_wiki_page_editor": "reddit.Wiki.post_api_wiki_alloweditor_add",
  "remove_wiki_page_editor": "reddit.Wiki.post_api_wiki_alloweditor_del",
  "perform_wiki_editor_action": "reddit.Wiki.post_api_wiki_alloweditor_act",
  "edit_wiki_page_content": "reddit.Wiki.post_api_wiki_edit",
  "hide_wiki_page_revision": "reddit.Wiki.post_api_wiki_hide",
  "revert_wiki_page_to_revision": "reddit.Wiki.post_api_wiki_revert",
  "get_wiki_page_discussions": "reddit.Wiki.get_wiki_discussions_page",
  "get_all_wiki_pages": "reddit.Wiki.get_wiki_pages",
  "get_all_wiki_revisions": "reddit.Wiki.get_wiki_revisions",
  "get_wiki_page_revisions": "reddit.Wiki.get_wiki_revisions_page",
  "get_wiki_page_settings": "reddit.Wiki.get_wiki_settings_page",
  "get_wiki_page_content": "reddit.Wiki.get_wiki_page",
  "check_captcha_requirement": "reddit.Captcha.get_api_needs_captcha",
  "add_post_to_collection": "reddit.Collections.post_api_v1_collections_add_post_to_collection",
  "get_collection_info": "reddit.Collections.get_api_v1_collections_collection",
  "create_collection": "reddit.Collections.post_api_v1_collections_create_collection",
  "delete_collection": "reddit.Collections.post_api_v1_collections_delete_collection",
  "remove_post_from_collection": "reddit.Collections.post_api_v1_collections_remove_post_in_collection",
  "reorder_collection_posts": "reddit.Collections.post_api_v1_collections_reorder_collection",
  "get_subreddit_collections": "reddit.Collections.get_api_v1_collections_subreddit_collections",
  "update_collection_description": "reddit.Collections.post_api_v1_collections_update_collection_description",
  "update_collection_display_layout": "reddit.Collections.post_api_v1_collections_update_collection_display_layout",
  "update_collection_title": "reddit.Collections.post_api_v1_collections_update_collection_title",
  "add_subreddit_emoji": "reddit.Emoji.post_api_v1_subreddit_emoji_json",
  "delete_subreddit_emoji": "reddit.Emoji.delete_api_v1_subreddit_emoji_emoji_name",
  "get_emoji_s3_upload_lease": "reddit.Emoji.post_api_v1_subreddit_emoji_asset_upload_s3_json",
  "set_subreddit_emoji_custom_size": "reddit.Emoji.post_api_v1_subreddit_emoji_custom_size",
  "get_all_subreddit_emojis": "reddit.Emoji.get_api_v1_subreddit_emojis_all",
  "block_user_via_message": "reddit.Messages.post_api_block",
  "collapse_messages": "reddit.Messages.post_api_collapse_message",
  "compose_message": "reddit.Messages.post_api_compose",
  "delete_message": "reddit.Messages.post_api_del_msg",
  "mark_all_messages_as_read": "reddit.Messages.post_api_read_all_messages",
  "mark_messages_as_read": "reddit.Messages.post_api_read_message",
  "unblock_subreddit_messaging": "reddit.Messages.post_api_unblock_subreddit",
  "uncollapse_messages": "reddit.Messages.post_api_uncollapse_message",
  "mark_messages_as_unread": "reddit.Messages.post_api_unread_message",
  "get_inbox_messages": "reddit.Messages.get_message_inbox",
  "get_sent_messages": "reddit.Messages.get_message_sent",
  "get_unread_messages": "reddit.Messages.get_message_unread",
  "get_messages_by_mailbox": "reddit.Messages.get_message_where",
  "submit_comment": "reddit.LinksAndComments.post_api_comment",
  "delete_post_or_comment": "reddit.LinksAndComments.post_api_del",
  "edit_post_or_comment_text": "reddit.LinksAndComments.post_api_editusertext",
  "follow_or_unfollow_post": "reddit.LinksAndComments.post_api_follow_post",
  "hide_posts": "reddit.LinksAndComments.post_api_hide",
  "get_items_info": "reddit.LinksAndComments.get_api_info",
  "lock_item": "reddit.LinksAndComments.post_api_lock",
  "mark_post_nsfw": "reddit.LinksAndComments.post_api_marknsfw",
  "get_more_comments": "reddit.LinksAndComments.get_api_morechildren",
  "report_item": "reddit.LinksAndComments.post_api_report",
  "save_item": "reddit.LinksAndComments.post_api_save",
  "get_saved_categories": "reddit.LinksAndComments.get_api_saved_categories",
  "toggle_item_replies": "reddit.LinksAndComments.post_api_sendreplies",
  "set_post_contest_mode": "reddit.LinksAndComments.post_api_set_contest_mode",
  "set_post_sticky_status": "reddit.LinksAndComments.post_api_set_subreddit_sticky",
  "set_post_suggested_sort": "reddit.LinksAndComments.post_api_set_suggested_sort",
  "mark_post_spoiler": "reddit.LinksAndComments.post_api_spoiler",
  "store_recent_visits": "reddit.LinksAndComments.post_api_store_visits",
  "submit_post": "reddit.LinksAndComments.post_api_submit",
  "unhide_posts": "reddit.LinksAndComments.post_api_unhide",
  "unlock_item": "reddit.LinksAndComments.post_api_unlock",
  "unmark_post_nsfw": "reddit.LinksAndComments.post_api_unmarknsfw",
  "unsave_item": "reddit.LinksAndComments.post_api_unsave",
  "unmark_post_spoiler": "reddit.LinksAndComments.post_api_unspoiler",
  "vote_on_item": "reddit.LinksAndComments.post_api_vote",
  "get_banned_users": "reddit.Subreddits.get_about_banned",
  "get_approved_submitters": "reddit.Subreddits.get_about_contributors",
  "get_subreddit_moderators": "reddit.Subreddits.get_about_moderators",
  "get_muted_users": "reddit.Subreddits.get_about_muted",
  "get_wiki_banned_users": "reddit.Subreddits.get_about_wikibanned",
  "get_approved_wiki_contributors": "reddit.Subreddits.get_about_wikicontributors",
  "get_users_by_category": "reddit.Subreddits.get_about_where",
  "delete_subreddit_banner": "reddit.Subreddits.post_api_delete_sr_banner",
  "delete_subreddit_header": "reddit.Subreddits.post_api_delete_sr_header",
  "delete_subreddit_icon": "reddit.Subreddits.post_api_delete_sr_icon",
  "delete_subreddit_stylesheet_image": "reddit.Subreddits.post_api_delete_sr_img",
  "recommend_related_subreddits": "reddit.Subreddits.get_api_recommend_sr_srnames",
  "search_subreddit_names": "reddit.Subreddits.get_api_search_reddit_names",
  "search_subreddits_by_title_description": "reddit.Subreddits.post_api_search_subreddits",
  "create_or_edit_subreddit": "reddit.Subreddits.post_api_site_admin",
  "get_subreddit_submit_text": "reddit.Subreddits.get_api_submit_text",
  "get_subreddit_autocomplete_suggestions_legacy": "reddit.Subreddits.get_api_subreddit_autocomplete",
  "get_subreddit_autocomplete_suggestions": "reddit.Subreddits.get_api_subreddit_autocomplete_v2",
  "update_subreddit_stylesheet": "reddit.Subreddits.post_api_subreddit_stylesheet",
  "subscribe_or_unsubscribe_subreddit": "reddit.Subreddits.post_api_subscribe",
  "upload_subreddit_stylesheet_image": "reddit.Subreddits.post_api_upload_sr_img",
  "get_subreddit_post_requirements": "reddit.Subreddits.get_api_v1_subreddit_post_requirements",
  "get_subreddit_info": "reddit.Subreddits.get_r_subreddit_about",
  "get_subreddit_editing_settings": "reddit.Subreddits.get_r_subreddit_about_edit",
  "get_subreddit_rules": "reddit.Subreddits.get_r_subreddit_about_rules",
  "get_subreddit_traffic_stats": "reddit.Subreddits.get_r_subreddit_about_traffic",
  "get_subreddit_sidebar": "reddit.Subreddits.get_sidebar",
  "get_stickied_post_ids": "reddit.Subreddits.get_sticky",
  "get_default_subreddits": "reddit.Subreddits.get_subreddits_default",
  "get_gold_subreddits": "reddit.Subreddits.get_subreddits_gold",
  "get_my_contributor_subreddits": "reddit.Subreddits.get_subreddits_mine_contributor",
  "get_my_moderator_subreddits": "reddit.Subreddits.get_subreddits_mine_moderator",
  "get_my_streaming_subreddits": "reddit.Subreddits.get_subreddits_mine_streams",
  "get_my_subscribed_subreddits": "reddit.Subreddits.get_subreddits_mine_subscriber",
  "get_my_subreddits_by_category": "reddit.Subreddits.get_subreddits_mine_where",
  "get_new_subreddits": "reddit.Subreddits.get_subreddits_new",
  "get_popular_subreddits": "reddit.Subreddits.get_subreddits_popular",
  "search_subreddits_by_name_or_topic": "reddit.Subreddits.get_subreddits_search",
  "get_subreddits_by_category": "reddit.Subreddits.get_subreddits_where",
  "get_newest_users": "reddit.Subreddits.get_users_new",
  "get_popular_users": "reddit.Subreddits.get_users_popular",
  "search_users_by_name": "reddit.Subreddits.get_users_search",
  "get_users_by_list_category": "reddit.Subreddits.get_users_where"
}

def __getattr__(name: str):
    return resolve_function_import(name, _function_map, error_simulator)

def __dir__():
    return sorted(set(globals().keys()) | set(_function_map.keys()))

__all__ = list(_function_map.keys())
